services:
  postgres-db : 
    image : postgres:15
    environment :
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB : postgres
    healthcheck :
      test : ["CMD-SHELL", "pg_isready -U postgres"]
      interval : 5s
      retries : 5
      start_period : 10s
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

volumes:
  postgres-db-volume: